import graphics.circle,graphics.rectangle
import graphics.degraphics.cuboid,graphics.degraphics.sphere
print("circle")
r=int(input('Enter radius of circle '))
print("Area ")
print(graphics.circle.areac(r))
print("Perimeter ")
print(graphics.circle.peric(r))
print('')
print("Rectangle")
l=int(input('Enter length of rectangle '))
b=int(input('Enter bredth of rectangle '))
print('Area')
print(graphics.rectangle.arearect(l,b))
print('Perimeter')
print(graphics.rectangle.perirect(l,b))

print('')
print("Cuboid")
a=int(input('Enter radius of cuboid '))
print('Area')
print(graphics.degraphics.cuboid.areacu(a))
print('Perimeter')
print(graphics.degraphics.cuboid.volcu(a))
print('')
print("Sphere")
a=int(input('Enter radius of sphere '))
print('Area')
print(graphics.degraphics.sphere.areasp(a))
print('Perimeter')
print(graphics.degraphics.sphere.volsp(a))
